AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable
  Exclude:
    - test/dummy/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
